### ISSUE TITLE
Switch the View to Blazor

### ISSUE THREAD

**Issue by andrii-malakhovtsev** [malandrii/sea-battle-game-winforms#20]
Switch from Windows Forms to Blazor Web Assembly for cross-platform (both applications and development possiblities)

Think of how I will handle the legacy version to save it, and save it's READme file.

**Comment by malakhovtsev** [comment]
Since the project is relatively simple, think of co-existance of Winforms and Blazor Views to get experience on working on two separate versions with the same Model

**Comment by malakhovtsev** [comment]
Use GitHub projects for separating issues for WinForms and Blazor versions
